version: "3.8"

services:
  app:
    image: ghcr.io/jscongdon/hoa_survey:develop
    container_name: hoa-survey-dev
    working_dir: /app
    command: bash -lc "if [ ! -d node_modules ]; then npm ci --legacy-peer-deps; fi && ./startup.sh"
    restart: unless-stopped
    tty: true
    ports:
      - "3001:3000"
    volumes:
      - ./:/app:cached
      - node-modules:/app/node_modules
      - hoa-survey-data:/data
      - ./public/uploads:/app/public/uploads
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api/setup/status",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  node-modules: {}
  hoa-survey-data: {}
