version: "3.8"

services:
  app:
    image: ghcr.io/jscongdon/hoa_survey:latest
    container_name: hoa_survey
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - hoa_survey_data:/data
    environment:
      - DATABASE_URL=file:/data/hoa-survey.db
      - NODE_ENV=production
      # Update PRODUCTION_URL with your actual domain
      - PRODUCTION_URL=${PRODUCTION_URL:-https://survey.yourdomain.com}
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api/setup/status",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  hoa_survey_data:
    driver: local
